version: '3.8'

services:

  mysql:
    image: mariadb
    container_name: buygames_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./tests/create.db.sql:/docker-entrypoint-initdb.d/create.db.sql:ro
      - mysql_vol:/var/lib/mysql

  db-php:
    build: .
    image: db-php
    container_name: db-php
    depends_on:
      - mysql
    environment:
      DB_DSN: mysql:dbname=db;host=mysql
      DB_USER: root
      DB_PASS: root
    volumes:
    - "./:/opt/project/"

volumes:
  mysql_vol:
